### ISSUE TITLE
I want to be a beta tester.

### ISSUE THREAD

**Issue by cdkw2** [spectrumgamer75/Infonata#3]
Hello, I am a frequent user of you All is well program, I would like to use your other projects too. I am on a raspberry pi BTW, so feel free to use me as your beta tester. I would love to help you improve your scripts. You can contact me here: **cdkw2#3833**

**Comment by Spectrum75** [comment]
Sure, will let you know if I need any beta testing via discord. Thanks for asking btw :smiley:
